# Generated by Django 5.0.3 on 2024-04-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_equipo_delete_article_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='bandera',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
