# Generated by Django 5.0.3 on 2024-04-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_equipo_bandera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fuerza',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='partidos_empatados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='partidos_ganados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='partidos_jugados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='partidos_perdidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='precision',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='puntos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='resistencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='velocidad',
            field=models.IntegerField(default=0),
        ),
    ]
