# Generated by Django 5.0.4 on 2024-05-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_equipo_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='precision',
            field=models.CharField(max_length=10),
        ),
    ]
